name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest docker toml

      - name: Run linter
        run: flake8 . --count --show-source --statistics

      - name: Run tests
        run: pytest
  release:
    needs: test-and-lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 pytest docker toml setuptools wheel

      - name: Install deb dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential python3-setuptools python3-all debhelper python3-stdeb fakeroot python-all

      - name: Build package
        run: python3 setup.py --command-packages=stdeb.command bdist_deb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/*.deb
          asset_name: docker-resource-limiter-${{ github.ref }}.deb
          asset_content_type: application/vnd.debian.binary-package
